from fastapi import FastAPI
from storage import city_data, alerts_store
import threading
from app import run_engine
from datetime import datetime

# create FastAPI app instance
app = FastAPI()

# list of valid zones in the system (used for validation)
# keeping this strict so no unknown zone is processed
VALID_ZONES = [
    "thane_zone_1",
    "thane_zone_2",
    "mumbai_zone_1",
    "mumbai_zone_2",
    "navi_mumbai_zone_1",
    "navi_mumbai_zone_2"
]

# this runs automatically when the server starts
# starting background engine in a separate thread so API remains responsive
@app.on_event("startup")
def start_engine():
    threading.Thread(target=run_engine, daemon=True).start()


# ---------------------- API 1 ----------------------
# returns latest traffic data for a specific zone
@app.get("/zone/traffic")
def zone_traffic(zone_id: str):

    # check if zone_id is valid
    if zone_id not in VALID_ZONES:
        return {"error": "invalid zone_id"}

    # fetch all records for this zone
    data_list = city_data.get(zone_id, [])

    # if no data available yet, return default response
    if not data_list:
        return {
            "zone_id": zone_id,
            "traffic_density": 0,
            "violation_count": 0,
            "congestion_level": "LOW",
            "timestamp": datetime.utcnow().isoformat(),
            "trace_id": f"empty_{zone_id}"  # helps in debugging empty cases
        }

    # take latest record (last inserted)
    d = data_list[-1]

    # prepare response based on latest data
    return {
        "zone_id": d["zone_id"],
        "traffic_density": d["traffic_density"],
        "violation_count": d["violation_count"],
        # simple rule: density > 50 means HIGH congestion
        "congestion_level": "HIGH" if d["traffic_density"] > 50 else "LOW",
        "timestamp": d["timestamp"],
        "trace_id": d["trace_id"]
    }


# ---------------------- API 2 ----------------------
# returns current state of all zones at once
@app.get("/zone/state")
def zone_state():

    result = []

    # iterate over all predefined zones
    for zone_id in VALID_ZONES:

        data_list = city_data.get(zone_id, [])

        # if no data found for a zone, send default values
        if not data_list:
            result.append({
                "zone_id": zone_id,
                "traffic_density": 0,
                "violation_count": 0,
                "congestion_level": "LOW",
                "timestamp": datetime.utcnow().isoformat(),
                "trace_id": f"empty_{zone_id}"
            })
            continue

        # take latest record
        d = data_list[-1]

        # append processed data to result list
        result.append({
            "zone_id": d["zone_id"],
            "traffic_density": d["traffic_density"],
            "violation_count": d["violation_count"],
            "congestion_level": "HIGH" if d["traffic_density"] > 50 else "LOW",
            "timestamp": d["timestamp"],
            "trace_id": d["trace_id"]
        })

    return result


# ---------------------- API 3 ----------------------
# returns all alerts generated by the system
@app.get("/alerts")
def alerts():
    return alerts_store